import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RocketChatClient } from "../client.js";

/**
 * Channel Management
 * Create, configure, and manage channels — set topics, archive stale ones, and bulk-invite members from a team
 *
 * Generated by mcp-generator — contains real decision logic,
 * not just a thin API wrapper.
 */
export function registerChannelManagement(
  server: McpServer,
  client: RocketChatClient,
): void {
  server.tool(
    "rc_manage_channel",
    "Create or update a channel: sets topic/description, invites a list of members, and archives if requested. Handles missing members gracefully.",
    {
      channelName: z.string().describe("Channel name to create or update"),
      topic: z.string().describe("Channel topic").optional(),
      members: z.array(z.string()).describe("Usernames to invite").optional(),
      shouldArchive: z.boolean().describe("Archive the channel instead of updating").optional(),
    },
    async ({ channelName, topic, members, shouldArchive }) => {
  let findChannel: any = null;
  try {
    findChannel = await client.get("/api/v1/channels.info", {
      roomName: channelName,
    });
  } catch (err) {
  }
  if (findChannel?.channel != null) {
    let setTopic: any = null;
    try {
    setTopic = await client.post("/api/v1/channels.setTopic", {
    roomId: channelId,
    topic: topic,
    });
    } catch (err) {
    }
    let inviteMembers: any = null;
    try {
    inviteMembers = await client.post("/api/v1/channels.invite", {
    roomId: channelId,
    userId: memberId,
    });
    } catch (err) {
    }
  } else {
    const createChannel = await client.post("/api/v1/channels.create", {
    name: channelName,
    members: members,
    });
  }
  const archiveChannel = await client.post("/api/v1/channels.archive", {
      roomId: channelId,
    });

      const result = { success: true };
      return {
        content: [{ type: "text" as const, text: JSON.stringify(result) }],
      };
    },
  );
}
