import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RocketChatClient } from "../client.js";

/**
 * Content Moderation
 * Review reported content, take action based on severity (warn user, delete message, deactivate account), and log the moderation action
 *
 * Generated by mcp-generator — contains real decision logic,
 * not just a thin API wrapper.
 */
export function registerContentModeration(
  server: McpServer,
  client: RocketChatClient,
): void {
  server.tool(
    "rc_moderate_content",
    "Review and act on reported content: fetches reports, decides action based on severity (warn/delete/deactivate), and logs the result to a moderation channel.",
    {
      userId: z.string().describe("The reported user's ID"),
      severity: z.string().describe("Severity level: low, medium, high"),
      moderationChannelName: z.string().describe("Channel to log moderation actions").optional(),
    },
    async ({ userId, severity, moderationChannelName }) => {
  const getReports = await client.get("/api/v1/moderation.reportsByUsers");
  const getUserInfo = await client.get("/api/v1/users.info", {
      userId: userId,
    });
  if (severity === "low" || severity === "medium") {
    let warnUser: any = null;
    try {
    warnUser = await client.post("/api/v1/chat.postMessage", {
    channel: `@${userInfo.user.username}`,
    text: "Your recent content has been flagged. Please review our community guidelines.",
    });
    } catch (err) {
    }
  } else {
    const deactivateUser = await client.post("/api/v1/users.setActiveStatus", {
    activeStatus: false,
    userId: userId,
    });
  }
  let dismissReports: any = null;
  try {
    dismissReports = await client.post("/api/v1/moderation.dismissReports", {
      userId: userId,
    });
  } catch (err) {
  }
  let logAction: any = null;
  try {
    logAction = await client.post("/api/v1/chat.postMessage", {
      channel: moderationChannelName,
      text: logMessage,
    });
  } catch (err) {
  }

      const result = { success: true };
      return {
        content: [{ type: "text" as const, text: JSON.stringify(result) }],
      };
    },
  );
}
