import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RocketChatClient } from "../client.js";

/**
 * Onboard Team Member
 * Onboard a new team member by creating their account, adding them to the right channels based on their role, and sending a welcome message
 *
 * Generated by mcp-generator — contains real decision logic,
 * not just a thin API wrapper.
 */
export function registerOnboardTeamMember(
  server: McpServer,
  client: RocketChatClient,
): void {
  server.tool(
    "rc_onboard_team_member",
    "Onboard a new team member: creates account if needed, adds to role-appropriate channels, sends welcome DM. Handles failures per-step without aborting the whole operation.",
    {
      username: z.string().describe("Username for the new member"),
      email: z.string().describe("Email address"),
      displayName: z.string().describe("Display name"),
      role: z.string().describe("Team role: developer, support, design, or default"),
      welcomeMessage: z.string().describe("Custom welcome message (optional)").optional(),
    },
    async ({ username, email, displayName, role, welcomeMessage }) => {
  const checkUserExists = await client.get("/api/v1/users.info", {
      username: username,
    });
  if (checkUserExists?.user != null) {
    const resolveChannels = await client.get("/api/v1/channels.list");
  } else {
    const createUser = await client.post("/api/v1/users.create", {
    username: username,
    email: email,
    name: displayName,
    password: crypto.randomUUID().slice(0, 16),
    roles: ["user"],
    });
  }
  let inviteToChannels: any = null;
  try {
    inviteToChannels = await client.post("/api/v1/channels.invite", {
      roomId: channelId,
      userId: userId,
    });
  } catch (err) {
  }
  let sendWelcomeDm: any = null;
  try {
    sendWelcomeDm = await client.post("/api/v1/chat.postMessage", {
      channel: `@${username}`,
      text: welcomeText,
    });
  } catch (err) {
  }

      const result = { success: true };
      return {
        content: [{ type: "text" as const, text: JSON.stringify(result) }],
      };
    },
  );
}
