import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RocketChatClient } from "../client.js";

/**
 * Minimal Chatbot
 * The absolute minimum: read messages from a channel and post replies. Baseline for token savings comparison.
 *
 * Generated by mcp-generator — contains real decision logic,
 * not just a thin API wrapper.
 */
export function registerMinimalChatbot(
  server: McpServer,
  client: RocketChatClient,
): void {
  server.tool(
    "rc_chatbot_reply",
    "Read recent messages from a channel and post a reply. The simplest possible workflow for baseline token comparison.",
    {
      channelName: z.string().describe("Channel to read from and reply to"),
      replyText: z.string().describe("Reply message text"),
    },
    async ({ channelName, replyText }) => {
  const getChannel = await client.get("/api/v1/channels.info", {
      roomName: channelName,
    });
  const getMessages = await client.get("/api/v1/channels.history", {
      roomId: getChannel.channel._id,
      count: 10,
    });
  let sendReply: any = null;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      sendReply = await client.post("/api/v1/chat.postMessage", {
      roomId: getChannel.channel._id,
      text: replyText,
    });
      break;
    } catch (err) {
      if (attempt === 1) throw err;
    }
  }

      const result = { success: true };
      return {
        content: [{ type: "text" as const, text: JSON.stringify(result) }],
      };
    },
  );
}
