import type { ApiCategory, ApiEndpoint } from "../../types/index.js";

/**
 * Curated API catalog for Rocket.Chat.
 * These are the endpoints referenced by workflow templates.
 * Not all 547 endpoints — only those needed for the 12 workflows.
 */

export const RC_CATEGORIES: ApiCategory[] = [
  {
    id: "authentication",
    label: "Authentication",
    description: "Login, logout, and token management",
    operationIds: ["login", "logout", "me"],
  },
  {
    id: "messaging",
    label: "Messaging",
    description: "Send, update, delete, and search messages",
    operationIds: [
      "chat.postMessage",
      "chat.update",
      "chat.delete",
      "chat.search",
      "chat.pinMessage",
      "chat.starMessage",
      "chat.react",
      "chat.getMessageReadReceipts",
    ],
  },
  {
    id: "channels",
    label: "Channels",
    description: "Create, manage, and query channels",
    operationIds: [
      "channels.create",
      "channels.delete",
      "channels.archive",
      "channels.unarchive",
      "channels.info",
      "channels.list",
      "channels.list.joined",
      "channels.history",
      "channels.invite",
      "channels.kick",
      "channels.members",
      "channels.setTopic",
      "channels.setDescription",
      "channels.setPurpose",
    ],
  },
  {
    id: "users",
    label: "Users",
    description: "User management, info, and status",
    operationIds: [
      "users.create",
      "users.update",
      "users.delete",
      "users.info",
      "users.list",
      "users.setStatus",
      "users.getStatus",
      "users.setAvatar",
      "users.setActiveStatus",
      "users.createToken",
    ],
  },
  {
    id: "rooms",
    label: "Rooms",
    description: "Room operations, notifications, and settings",
    operationIds: [
      "rooms.info",
      "rooms.get",
      "rooms.cleanHistory",
      "rooms.upload",
      "rooms.saveNotification",
      "rooms.favorite",
    ],
  },
  {
    id: "dm",
    label: "Direct Messages",
    description: "Direct message operations",
    operationIds: ["dm.create", "dm.list", "dm.history", "dm.close"],
  },
  {
    id: "teams",
    label: "Teams",
    description: "Team management and membership",
    operationIds: [
      "teams.create",
      "teams.delete",
      "teams.addMembers",
      "teams.removeMembers",
      "teams.members",
      "teams.listAll",
      "teams.info",
      "teams.listRooms",
    ],
  },
  {
    id: "omnichannel",
    label: "Omnichannel",
    description: "Livechat and omnichannel operations",
    operationIds: [
      "livechat/rooms",
      "livechat/room.close",
      "livechat/room.transfer",
      "livechat/message",
      "livechat/agent",
      "livechat/visitors.info",
      "livechat/queue",
    ],
  },
  {
    id: "integrations",
    label: "Integrations",
    description: "Webhook and integration management",
    operationIds: [
      "integrations.create",
      "integrations.remove",
      "integrations.list",
      "integrations.get",
      "integrations.update",
    ],
  },
  {
    id: "statistics",
    label: "Statistics",
    description: "Server statistics and analytics",
    operationIds: ["statistics", "statistics.list"],
  },
  {
    id: "moderation",
    label: "Moderation",
    description: "Content moderation and reporting",
    operationIds: [
      "moderation.reportsByUsers",
      "moderation.dismissReports",
      "moderation.user-reported-messages",
      "moderation.user-delete-reported-messages",
    ],
  },
  {
    id: "notifications",
    label: "Notifications",
    description: "Push notifications and alerts",
    operationIds: ["push.token", "push.get"],
  },
];

export const RC_ENDPOINTS: ApiEndpoint[] = [
  // === Authentication ===
  {
    operationId: "login",
    method: "POST",
    path: "/api/v1/login",
    summary: "Authenticate user and get auth token",
    category: "authentication",
    parameters: [],
    requestBody: { contentType: "application/json", schema: { user: "string", password: "string" }, required: true },
    requiresAuth: false,
  },
  {
    operationId: "me",
    method: "GET",
    path: "/api/v1/me",
    summary: "Get current user info",
    category: "authentication",
    parameters: [],
    requiresAuth: true,
  },

  // === Messaging ===
  {
    operationId: "chat.postMessage",
    method: "POST",
    path: "/api/v1/chat.postMessage",
    summary: "Send a message to a channel or user",
    category: "messaging",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string", text: "string", channel: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "chat.update",
    method: "POST",
    path: "/api/v1/chat.update",
    summary: "Update an existing message",
    category: "messaging",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string", msgId: "string", text: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "chat.delete",
    method: "POST",
    path: "/api/v1/chat.delete",
    summary: "Delete a message",
    category: "messaging",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string", msgId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "chat.search",
    method: "GET",
    path: "/api/v1/chat.search",
    summary: "Search messages in a room",
    category: "messaging",
    parameters: [
      { name: "roomId", in: "query", description: "Room ID", required: true, type: "string" },
      { name: "searchText", in: "query", description: "Text to search", required: true, type: "string" },
    ],
    requiresAuth: true,
  },
  {
    operationId: "chat.pinMessage",
    method: "POST",
    path: "/api/v1/chat.pinMessage",
    summary: "Pin a message",
    category: "messaging",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { messageId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "chat.react",
    method: "POST",
    path: "/api/v1/chat.react",
    summary: "React to a message with an emoji",
    category: "messaging",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { emoji: "string", messageId: "string" },
      required: true,
    },
    requiresAuth: true,
  },

  // === Channels ===
  {
    operationId: "channels.create",
    method: "POST",
    path: "/api/v1/channels.create",
    summary: "Create a new channel",
    category: "channels",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { name: "string", members: "string[]", readOnly: "boolean" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "channels.delete",
    method: "POST",
    path: "/api/v1/channels.delete",
    summary: "Delete a channel",
    category: "channels",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "channels.archive",
    method: "POST",
    path: "/api/v1/channels.archive",
    summary: "Archive a channel",
    category: "channels",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "channels.info",
    method: "GET",
    path: "/api/v1/channels.info",
    summary: "Get channel information",
    category: "channels",
    parameters: [
      { name: "roomId", in: "query", description: "Room ID", required: false, type: "string" },
      { name: "roomName", in: "query", description: "Room name", required: false, type: "string" },
    ],
    requiresAuth: true,
  },
  {
    operationId: "channels.list",
    method: "GET",
    path: "/api/v1/channels.list",
    summary: "List all channels",
    category: "channels",
    parameters: [],
    requiresAuth: true,
  },
  {
    operationId: "channels.list.joined",
    method: "GET",
    path: "/api/v1/channels.list.joined",
    summary: "List channels the user has joined",
    category: "channels",
    parameters: [],
    requiresAuth: true,
  },
  {
    operationId: "channels.history",
    method: "GET",
    path: "/api/v1/channels.history",
    summary: "Get channel message history",
    category: "channels",
    parameters: [
      { name: "roomId", in: "query", description: "Room ID", required: true, type: "string" },
      { name: "count", in: "query", description: "Number of messages", required: false, type: "number" },
    ],
    requiresAuth: true,
  },
  {
    operationId: "channels.invite",
    method: "POST",
    path: "/api/v1/channels.invite",
    summary: "Invite a user to a channel",
    category: "channels",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string", userId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "channels.kick",
    method: "POST",
    path: "/api/v1/channels.kick",
    summary: "Remove a user from a channel",
    category: "channels",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string", userId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "channels.members",
    method: "GET",
    path: "/api/v1/channels.members",
    summary: "List members of a channel",
    category: "channels",
    parameters: [
      { name: "roomId", in: "query", description: "Room ID", required: true, type: "string" },
    ],
    requiresAuth: true,
  },
  {
    operationId: "channels.setTopic",
    method: "POST",
    path: "/api/v1/channels.setTopic",
    summary: "Set channel topic",
    category: "channels",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string", topic: "string" },
      required: true,
    },
    requiresAuth: true,
  },

  // === Users ===
  {
    operationId: "users.create",
    method: "POST",
    path: "/api/v1/users.create",
    summary: "Create a new user",
    category: "users",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: {
        username: "string",
        email: "string",
        name: "string",
        password: "string",
        roles: "string[]",
      },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "users.update",
    method: "POST",
    path: "/api/v1/users.update",
    summary: "Update user data",
    category: "users",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { userId: "string", data: "object" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "users.delete",
    method: "POST",
    path: "/api/v1/users.delete",
    summary: "Delete a user",
    category: "users",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { userId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "users.info",
    method: "GET",
    path: "/api/v1/users.info",
    summary: "Get user information",
    category: "users",
    parameters: [
      { name: "username", in: "query", description: "Username", required: false, type: "string" },
      { name: "userId", in: "query", description: "User ID", required: false, type: "string" },
    ],
    requiresAuth: true,
  },
  {
    operationId: "users.list",
    method: "GET",
    path: "/api/v1/users.list",
    summary: "List all users",
    category: "users",
    parameters: [],
    requiresAuth: true,
  },
  {
    operationId: "users.setStatus",
    method: "POST",
    path: "/api/v1/users.setStatus",
    summary: "Set user status",
    category: "users",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { message: "string", status: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "users.getStatus",
    method: "GET",
    path: "/api/v1/users.getStatus",
    summary: "Get user status",
    category: "users",
    parameters: [
      { name: "userId", in: "query", description: "User ID", required: true, type: "string" },
    ],
    requiresAuth: true,
  },
  {
    operationId: "users.setActiveStatus",
    method: "POST",
    path: "/api/v1/users.setActiveStatus",
    summary: "Activate or deactivate a user",
    category: "users",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { activeStatus: "boolean", userId: "string" },
      required: true,
    },
    requiresAuth: true,
  },

  // === DM ===
  {
    operationId: "dm.create",
    method: "POST",
    path: "/api/v1/dm.create",
    summary: "Create a direct message session",
    category: "dm",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { username: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "dm.list",
    method: "GET",
    path: "/api/v1/dm.list",
    summary: "List direct message sessions",
    category: "dm",
    parameters: [],
    requiresAuth: true,
  },
  {
    operationId: "dm.history",
    method: "GET",
    path: "/api/v1/dm.history",
    summary: "Get DM history",
    category: "dm",
    parameters: [
      { name: "roomId", in: "query", description: "Room ID", required: true, type: "string" },
    ],
    requiresAuth: true,
  },

  // === Teams ===
  {
    operationId: "teams.create",
    method: "POST",
    path: "/api/v1/teams.create",
    summary: "Create a team",
    category: "teams",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { name: "string", type: "number", members: "string[]" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "teams.delete",
    method: "POST",
    path: "/api/v1/teams.delete",
    summary: "Delete a team",
    category: "teams",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { teamId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "teams.addMembers",
    method: "POST",
    path: "/api/v1/teams.addMembers",
    summary: "Add members to a team",
    category: "teams",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { teamId: "string", members: "object[]" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "teams.removeMembers",
    method: "POST",
    path: "/api/v1/teams.removeMembers",
    summary: "Remove members from a team",
    category: "teams",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { teamId: "string", members: "object[]" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "teams.members",
    method: "GET",
    path: "/api/v1/teams.members",
    summary: "List team members",
    category: "teams",
    parameters: [
      { name: "teamId", in: "query", description: "Team ID", required: true, type: "string" },
    ],
    requiresAuth: true,
  },
  {
    operationId: "teams.listAll",
    method: "GET",
    path: "/api/v1/teams.listAll",
    summary: "List all teams",
    category: "teams",
    parameters: [],
    requiresAuth: true,
  },
  {
    operationId: "teams.info",
    method: "GET",
    path: "/api/v1/teams.info",
    summary: "Get team info",
    category: "teams",
    parameters: [
      { name: "teamId", in: "query", description: "Team ID", required: true, type: "string" },
    ],
    requiresAuth: true,
  },

  // === Omnichannel ===
  {
    operationId: "livechat/rooms",
    method: "GET",
    path: "/api/v1/livechat/rooms",
    summary: "List livechat rooms",
    category: "omnichannel",
    parameters: [],
    requiresAuth: true,
  },
  {
    operationId: "livechat/room.close",
    method: "POST",
    path: "/api/v1/livechat/room.close",
    summary: "Close a livechat room",
    category: "omnichannel",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { rid: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "livechat/room.transfer",
    method: "POST",
    path: "/api/v1/livechat/room.transfer",
    summary: "Transfer a livechat room to another agent",
    category: "omnichannel",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { rid: "string", userId: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "livechat/message",
    method: "POST",
    path: "/api/v1/livechat/message",
    summary: "Send a livechat message",
    category: "omnichannel",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { rid: "string", msg: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "livechat/visitors.info",
    method: "GET",
    path: "/api/v1/livechat/visitors.info",
    summary: "Get visitor information",
    category: "omnichannel",
    parameters: [
      { name: "visitorId", in: "query", description: "Visitor ID", required: true, type: "string" },
    ],
    requiresAuth: true,
  },

  // === Integrations ===
  {
    operationId: "integrations.create",
    method: "POST",
    path: "/api/v1/integrations.create",
    summary: "Create a webhook integration",
    category: "integrations",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { type: "string", name: "string", channel: "string", scriptEnabled: "boolean", script: "string", event: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "integrations.remove",
    method: "POST",
    path: "/api/v1/integrations.remove",
    summary: "Remove an integration",
    category: "integrations",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { integrationId: "string", type: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "integrations.list",
    method: "GET",
    path: "/api/v1/integrations.list",
    summary: "List all integrations",
    category: "integrations",
    parameters: [],
    requiresAuth: true,
  },

  // === Statistics ===
  {
    operationId: "statistics",
    method: "GET",
    path: "/api/v1/statistics",
    summary: "Get server statistics",
    category: "statistics",
    parameters: [],
    requiresAuth: true,
  },
  {
    operationId: "statistics.list",
    method: "GET",
    path: "/api/v1/statistics.list",
    summary: "List statistics",
    category: "statistics",
    parameters: [],
    requiresAuth: true,
  },

  // === Moderation ===
  {
    operationId: "moderation.reportsByUsers",
    method: "GET",
    path: "/api/v1/moderation.reportsByUsers",
    summary: "Get moderation reports grouped by users",
    category: "moderation",
    parameters: [],
    requiresAuth: true,
  },
  {
    operationId: "moderation.dismissReports",
    method: "POST",
    path: "/api/v1/moderation.dismissReports",
    summary: "Dismiss moderation reports",
    category: "moderation",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { userId: "string" },
      required: true,
    },
    requiresAuth: true,
  },

  // === Rooms ===
  {
    operationId: "rooms.info",
    method: "GET",
    path: "/api/v1/rooms.info",
    summary: "Get room information",
    category: "rooms",
    parameters: [
      { name: "roomId", in: "query", description: "Room ID", required: true, type: "string" },
    ],
    requiresAuth: true,
  },
  {
    operationId: "rooms.upload",
    method: "POST",
    path: "/api/v1/rooms.upload",
    summary: "Upload a file to a room",
    category: "rooms",
    parameters: [],
    requestBody: {
      contentType: "multipart/form-data",
      schema: { file: "binary", description: "string" },
      required: true,
    },
    requiresAuth: true,
  },
  {
    operationId: "rooms.cleanHistory",
    method: "POST",
    path: "/api/v1/rooms.cleanHistory",
    summary: "Clean room message history",
    category: "rooms",
    parameters: [],
    requestBody: {
      contentType: "application/json",
      schema: { roomId: "string", latest: "string", oldest: "string" },
      required: true,
    },
    requiresAuth: true,
  },
];
